[versions]
kotlin = "1.9.0"
skie = "0.5.0"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.7.3" }
skie-annotations = { module = "co.touchlab.skie:configuration-annotations", version.ref = "skie" }
